#nextcloud
services:
  app:
    image: nextcloud:32.0.6-apache
    ports:
      - 2563:80
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${POSTGRES_DB}
      - MYSQL_USER=${POSTGRES_USER}
      - MYSQL_PASSWORD=${POSTGRES_PASSWORD}
      - MYSQL_HOST=database
      - OVERWRITEPROTOCOL=https
      - NC_maintenance_window_start=4
      - NC_default_phone_region=DE
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - database
      - redis
    depends_on:
      - redis

  redis:
    image: redis:8.6.0-alpine
    restart: always
    command: redis-server

  database:
    image: mariadb:12.2.2-noble
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${POSTGRES_PASSWORD}
      - MYSQL_PASSWORD=${POSTGRES_PASSWORD}
      - MYSQL_DATABASE=${POSTGRES_DB}
      - MYSQL_USER=${POSTGRES_USER}
      - TZ=Europe/Berlin

  cron:
    image: nextcloud:32.0.6-apache
    depends_on:
      - app
      - database
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped
    entrypoint: /cron.sh
    environment:
      - PHP_MEMORY_LIMIT=512M
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256

volumes:
  nextcloud:
  database:
